name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy website files
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "./*"
          target: ${{ secrets.DEPLOY_TARGET }}
          rm: true
          overwrite: true
          strip_components: 0
          debug: true
          exclude: ".git,.github"   # вот тут исключаем папки, которые ломают tar
