name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy website files
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "./*"           # все файлы в корне репо, кроме скрытых
          target: ${{ secrets.DEPLOY_TARGET }}
          rm: true               # удалить файлы на сервере перед копированием
          overwrite: true
          debug: true
